//
//  Foscam19810W.hpp
//  ipcams
//
//  Created by Tony Constantinides on 2/3/16.
//  Copyright © 2016 Eva Automation. All rights reserved.
//

#ifndef Foscam19810W_hpp
#define Foscam19810W_hpp
#include <string>

namespace IPCams {
    namespace FoscamMJPEG  {

class Foscam19810W
{
public:

    static void buildCompoundKeys();
};
static std::string CAMERA_IP_PORT;
static std::string AUTH;
        
//        "http://192.168.3.254:8090/";


// "&user=admin&pwd=L0g6r41P9D7q";
#define GET_STATUS_COMMAND "get_status.cgi?"

#define GET_CAMERA_PARAMS  "get_camera_params.cgi?"

#define CAMERA_CONTROL  "camera_control.cgi?"
#define CAMERA_COMMAND  "decoder_control.cgi?"
#define CAMERA_MISC     "set_misc.cgi?"
#define CGI_PROXY       "cgi-bin/CGIProxy.fcgi?"
#define SET_ALARM      "set_alarm.cgi?motion_armed1"
        
#define SET_ALARM_ONLY "set_alarm.cgi?"
#define UPLOAD_INTERVAL "upload_interval="
#define GET_LOG         "get_log.cgi"
#define MOTION_SENSITIVITY_0 "&motion_sensitivity=0"
#define MOTION_SENSITIVITY_1  "&motion_sensitivity=1"
#define MOTION_SENSITIVITY_2  "&motion_sensitivity=2"
#define MOTION_SENSITIVITY_3  "&motion_sensitivity=3"
#define MOTION_SENSITIVITY_4  "&motion_sensitivity=4"
#define MOTION_SENSITIVITY_5  "&motion_sensitivity=5"
#define MOTION_SENSITIVITY_6  "&motion_sensitivity=6"
#define MOTION_SENSITIVITY_7  "&motion_sensitivity=7"
#define MOTION_SENSITIVITY_8  "&motion_sensitivity=8"
#define GET_VIDEO_STREAM_TYPE  "cmd=getMainVideoStreamType"
#define GET_VIDEO_STREAM_MJPEG  "videostream.asf?"
#define RESOLUTION_640x480      "&resolution=32"
#define RESOLUTION_320x240      "&resolution=8"

#define RESOLUTON_640x480_EXPLICIT  "&resolution=640*480"
#define RESOLUTION_320x240_EXPLICIT  "&resolution=320x240"
#define FPS_MAX_RATE                 "&rate=0"
#define FPS_20                       "&rate=1"
#define FPS_15                       "&rate=3"
#define FPS_10                       "&rate6"
#define FPS_5                        "&rate=11"
#define FPS_4                        "&rate=12"
#define FPS_3                        "&rate=13"
#define FPS_2                        "&rate=14"
#define FPS_1                        "&rate=15"
#define FPS_EVERY_2_SECS             "&rate=17"
#define FPS_EVERY_3_SECS             "&rate=19"
#define FPS_EVERY_4_SECS             "&rate=21"
#define FPS_EVERY_5_SECS             "&rate=23"
#define FLIP_AND_MIRROR_NORMAL  "param=5&value=0"
#define FLIP                    "param=5&value=1"
#define FLIP_AND_MIRROR         "param=5&value=3"
#define MIRROR                  "param=5&value=2"
#define REBOOT_COMMAND          "reboot.cgi?"
#define IR_ON_COMMAND         "command=95"
#define IR_OFF_COMMAND        "command=94"
#define BLINK_LED_WHEN_CONNECTED_COMMAND "led_mode=0"
#define BLINK_LED_WHEN_SEARCHING_COMMAND "led_mode=1"
#define LED_ALWAYS_ON_COMMAND            "led_mode=2"
// add users to camera
#define CAMERA_ADMIN_ADDUSER "set_users.cgi?"
#define CAMERA_SNAPSHOT_COMMAND "snapshot.cgi?"
#define SNAPSHOT_FILENAME  "&next_url=test2"
#define ENABLE_ALARM_COMMAND "iolinkage=1"
#define DISABLED_ALARM_COMMAND "iolinkage=0"
#define PAN_DOWN "command=0&onestep=2"
#define PAN_UP "command=2&onestep=2"
#define PAN_LEFT "command=4&onestep=2"
#define PAN_RIGHT "command=6&onestep=2"
#define CENTER "command=25"
#define START_VERTICAL_PATROL "command=26"
#define STOP_VERTCAL_PATROL "command=27"
#define START_HORIZONTAL_PATROL "command=28"
#define STOP_HORIZONTAL_PATROL "command=29"
#define PTZ_CENTER_CAM_ON_STARTUP  "ptz_center_onstart=0"
#define PTZ_START_PATROL_IN_30SECS "ptz_auto_patrol_interval=30"
#define PTZ_START_PATROL_IN_5SECS  "ptz_auto_patrol_interval=5"
#define PTZ_STOP_PATROL "ptz_auto_patrol_type=0"
#define PTZ_SET_AUTO_PATROL_TYPE_HORIZONTAL "ptz_auto_patrol_type=1"
#define PTZ_SET_AUTO_PATROL_TYPE_VERTICAL   "ptz_auto_patrol_type=2"
#define PTZ_SET_AUTO_PATROL_BOTH "ptz_auto_patrol_type=3"
#define PTZ_PATROL_SPEED_DEFAULT "ptz_patrol_rate=20"
#define PTZ_PATROL_SPEED_FASTEST "ptz_patrol_rate=0"
#define PTX_PATROL_SPEED_SLOWEST "ptz_patrol_rate=100"
#define GOTO_CAM_PRESET_0 "command=31"
#define SET_CAM_PRESET_1  "command=32"
#define GOTO_CAM_PRESET_1 "command=33"
#define SET_CAM_PRESET_2  "command=34"
#define GOTO_CAM_PRESET_2 "command=35"
#define SET_CAM_PRESET_3  "command=36"
#define GOTO_CAM_PRESET_3 "command=37"
#define SET_CAM_TO_DEFAULT_REZ "param=0&value=0"
#define SET_CAM_TO_VGA_REZ "param=0&value=32"
#define SET_CAM_TO_QVGA_REZ "param=0&value=8"
#define CAM_MIN_BRIGHTNESS "param=1&value=0"
#define CAM_1_BRIGHTNESS   "param=1&value=17"
#define CAM_2_BRIGHTNESS   "param=1&value=34"
#define CAM_3_BRIGHTNESS   "param=1&value=51"
#define CAM_4_BRIGHTNESS   "param=1&value=68"
#define CAM_5_BRIGHTNESS   "param=1&value=85"
#define CAM_6_BRIGHTNESS   "param=1&value=102"
#define CAM_7_BRIGHTNESS   "param=1&value=119"
#define CAM_8_BRIGHTNESS   "param=1&value=136"
#define CAM_9_BRIGHTNESS   "param=1&value=153"
#define CAM_10_BRIGHTNESS  "param=1&value=170"
#define CAM_11_BRIGHTNESS  "param=1&value=187"
#define CAM_12_BRIGHTNESS  "param=1&value=204"
#define CAM_13_BRIGHTNESS  "param=1&value=221"
#define CAM_14_BRIGHTNESS  "param=1&value=238"
#define CAM_15_BRIGHTNESS  "param=1&value=255"
#define CAM_MIN_CONSTRAST  "param=2&value=0"
#define CAM_MID_CONSTRAST  "param=2&value=3"
#define CAM_MAX_CONSTRAST  "param=2&value=6"
#define CAM_SET_50HZ       "param=3&value=0"
#define CAM_SET_60HZ       "param=3&value=1"
#define CAM_SET_OUTDOORS   "param=3&value=2"
#define ENABLE_MAIL_WITH_ALARM "mail=1"
#define DISABLE_MAIL_WTH_ALARM "mail=0"


#define GET_STATUS                     CAMERA_IP_PORT + GET_STATUS_COMMAND + AUTH
#define CAMERA_GET_VIDEO_STREAM_TYPE   CAMERA_IP_PORT + CGI_PROXY + GET_VIDEO_STREAM_TYPE + AUTH
#define GET_CAMERA_PARAMS_COMMAND  CAMERA_IP_PORT + GET_CAMERA_PARAMS + AUTH 
// this way if getting the video stream if only for Foscom 18919W cama with MPEG-2 streaming over http
// get the video stream at 64x480(32) or 320x328(8)
#define GET_VIDEOSTREAM_640x480  CAMERA_IP_PORT + GET_VIDEO_STREAM_MJPEG  + AUTH + RESOLUTON_640x480_EXPLICIT
#define GET_VIDEOSTREAM_320x240  CAMERA_IP_PORT + GET_VIDEO_STREAM_MJPEG + AUTH + RESOLUTION_320x240_EXPLICIT

// set the frames per seconds assume 640x480
#define GET_VIDEOSTREAM_MAX_FPS  CAMERA_IP_PORT + GET_VIDEO_STREAM_MJPEG + AUTH + RESOLUTION_640x480  + FPS_MAX_RATE
#define GET_VIDEOSTREAM_20_FPS   CAMERA_IP_PORT + GET_VIDEO_STREAM_MJPEG + AUTH + RESOLUTION_640x480 + FPS_20
#define GET_VIDEOSTREAM_15_FPS   CAMERA_IP_PORT + GET_VIDEO_STREAM_MJPEG + AUTH + RESOLUTION_640x480 + FPS_15
#define GET_VIDEOSTREAM_10_FPS   CAMERA_IP_PORT + GET_VIDEO_STREAM_MJPEG + AUTH + RESOLUTION_640x480 + FPS_10
#define GET_VIDEOSTREAM_5_FPS    CAMERA_IP_PORT + GET_VIDEO_STREAM_MJPEG + AUTH + RESOLUTION_640x480 + FPS_5
#define GET_VIDEOSTREAM_4_FPS    CAMERA_IP_PORT + GET_VIDEO_STREAM_MJPEG + AUTH + RESOLUTION_640x480 + FPS_4
#define GET_VIDEOSTREAM_3_FPS    CAMERA_IP_PORT + GET_VIDEO_STREAM_MJPEG + AUTH + RESOLUTION_640x480 + FPS_3
#define GET_VIDEOSTREAM_2_FPS    CAMERA_IP_PORT + GET_VIDEO_STREAM_MJPEG + AUTH + RESOLUTION_640x480 + FPS_2
#define GET_VIDEOSTREAM_1_FPS    CAMERA_IP_PORT + GET_VIDEO_STREAM_MJPEG + AUTH + RESOLUTION_640x480 + FPS_1
#define GET_VIDEOSTREAM_EVERY_2SECS_FPS   CAMERA_IP_PORT + GET_VIDEO_STREAM_MJPEG + AUTH + RESOLUTION_640x480 + FPS_EVERY_2_SECS
#define GET_VIDEOSTREAM_EVERY_3SECS_FPS   CAMERA_IP_PORT + GET_VIDEO_STREAM_MJPEG + AUTH + RESOLUTION_640x480 + FPS_EVERY_3_SECS
#define GET_VIDEOSTREAM_EVERY_4SECS_FPS   CAMERA_IP_PORT + GET_VIDEO_STREAM_MJPEG + AUTH + RESOLUTION_640x480 + FPS_EVERY_4_SECS
#define GET_VIDEOSTREAM_EVERY_5SECS_FPS   CAMERA_IP_PORT + GET_VIDEO_STREAM_MJPEG + AUTH + RESOLUTION_640x480 + FPS_EVERY_5_SECS

// reboot camera (starts with IR on)
#define CAMERA_REBOOT  CAMERA_IP_PORT + REBOOT_COMMAND + AUTH
// turn IR on and off
#define CAMERA_IR_ON   CAMERA_IP_PORT + CAMERA_COMMAND + IR_ON_COMMAND  + AUTH
#define CAMERA_IR_OFF  CAMERA_IP_PORT + CAMERA_COMMAND + IR_OFF_COMMAND + AUTH
// set the green led activity led
#define CAMERIA_GREEN_LED_BLINKONLY_WHEN_CONNECTED  CAMERA_IP_PORT + CAMERA_MISC + BLINK_LED_WHEN_CONNECTED_COMMAND  + AUTH
#define CAMERIA_GREEN_LED_BLINKONLY_WHEN_SEARCHING  CAMERA_IP_PORT + CAMERA_MISC + BLINK_LED_WHEN_SEARCHING_COMMAND + AUTH
#define CAMERIA_GREEN_LED_ALWAYS_OFF    CAMERA_IP_PORT + CAMERA_MISC + LED_ALWAYS_ON_COMMAND  + AUTH

#define ADD_USER_TO_CAMERA  CAMERA_IP_PORT + CAMERA_ADMIN_ADDUSER + "user1=tonyc&pwd1=tonyc&pri=2" + AUTH
// displays the camera logs
#define CAMERA_GET_LOG      CAMERA_IP_PORT + GET_LOG + AUTH
// take a picture
#define CAMERA_TAKE_SNAPSHOT            CAMERA_IP_PORT + CAMERA_SNAPSHOT_COMMAND + AUTH  + SNAPSHOT_FILENAME
#define CAMERA_TAKE_SNAPSHOT_320x240    CAMERA_IP_PORT + CAMERA_SNAPSHOT_COMMAND + RESOLUTION_320x240 + AUTH  + SNAPSHOT_FILENAME
#define CAMERA_TAKE_SNAPSHOT_640x480    CAMERA_IP_PORT + CAMERA_SNAPSHOT_COMMAND + RESOLUTION_640x480 + AUTH  + SNAPSHOT_FILENAME

// camera movement
#define CAMERA_CONTROL_PAN_DOWN                 CAMERA_IP_PORT + CAMERA_COMMAND + PAN_DOWN + AUTH
#define CAMERA_CONTROL_PAN_UP                   CAMERA_IP_PORT + CAMERA_COMMAND + PAN_UP  + AUTH
#define CAMERA_CONTROL_PAN_LEFT                 CAMERA_IP_PORT + CAMERA_COMMAND + PAN_LEFT+ AUTH
#define CAMERA_CONTROL_PAN_RIGHT                CAMERA_IP_PORT + CAMERA_COMMAND + PAN_RIGHT + AUTH
#define CAMERA_CONTROL_CENTER                   CAMERA_IP_PORT + CAMERA_COMMAND + CENTER + AUTH
#define CAMERA_CONTROL_START_VERITICAL_PATROL   CAMERA_IP_PORT + CAMERA_COMMAND + START_VERTICAL_PATROL + AUTH
#define CAMERA_CONTROL_STOP_VERITICAL_PATROL    CAMERA_IP_PORT + CAMERA_COMMAND + STOP_VERTCAL_PATROL + AUTH
#define CAMERA_CONTROL_START_HORIZONTAL_PATROL  CAMERA_IP_PORT + CAMERA_COMMAND + START_HORIZONTAL_PATROL + AUTH
#define CAMERA_CONTROL_STOP_HORIZONTAL_PATROL   CAMERA_IP_PORT + CAMERA_COMMAND + STOP_HORIZONTAL_PATROL + AUTH
// control camera pan till zoon cabability and patrol interval
#define CAMERA_CONTROL_CENTER_ON_START     CAMERA_IP_PORT + CAMERA_MISC + PTZ_CENTER_CAM_ON_STARTUP + AUTH
#define CAMERA_START_PATROL_IN_30_SECONDS  CAMERA_IP_PORT + CAMERA_MISC + PTZ_START_PATROL_IN_30SECS + AUTH
#define CAMERA_START_PATROL_IN_5_SECONDS   CAMERA_IP_PORT + CAMERA_MISC +  PTZ_START_PATROL_IN_5SECS  + AUTH
#define CAMERA_PATROL_TYPE_STOP       CAMERA_IP_PORT + CAMERA_MISC + PTZ_STOP_PATROL + AUTH
#define CAMERA_PATROL_TYPE_HORIZONTAL CAMERA_IP_PORT + CAMERA_MISC + PTZ_SET_AUTO_PATROL_TYPE_HORIZONTAL + AUTH
#define CAMERA_PATROL_TYPE_VERTICAL   CAMERA_IP_PORT + CAMERA_MISC + PTZ_SET_AUTO_PATROL_TYPE_VERTICAL + AUTH
#define CAMERA_PATROL_TYPE_BOTH       CAMERA_IP_PORT + CAMERA_MISC + PTZ_SET_AUTO_PATROL_BOTH + AUTH
// control how fast the camera will patrol(both horizontal or vertically or both)
#define CAMERA_PATROL_SPEED_DEFAULT   CAMERA_IP_PORT + CAMERA_MISC + PTZ_PATROL_SPEED_DEFAULT + AUTH
#define CAMERA_PATROL_SPEED_FASTEST   CAMERA_IP_PORT + CAMERA_MISC + PTZ_PATROL_SPEED_FASTEST + AUTH
#define CAMERA_PATROL_SPEED_SLOWEST   CAMERA_IP_PORT + CAMERA_MISC + PTX_PATROL_SPEED_SLOWEST + AUTH

// go to camera presets 1 to 3
#define CAMERA_GO_PRESET_0   CAMERA_IP_PORT + CAMERA_COMMAND + GOTO_CAM_PRESET_0 + AUTH
#define CAMERA_SET_PRESET_1  CAMERA_IP_PORT + CAMERA_COMMAND + SET_CAM_PRESET_1 + AUTH
#define CAMERA_GO_PRESET_1   CAMERA_IP_PORT + CAMERA_COMMAND + GOTO_CAM_PRESET_1 + AUTH
#define CAMERA_SET_PRESET_2  CAMERA_IP_PORT + CAMERA_COMMAND + SET_CAM_PRESET_2 + AUTH
#define CAMERA_GO_PRESET_2   CAMERA_IP_PORT + CAMERA_COMMAND + GOTO_CAM_PRESET_2 + AUTH
#define CAMERA_SET_PRESET_3  CAMERA_IP_PORT + CAMERA_COMMAND + SET_CAM_PRESET_3 + AUTH
#define CAMERA_GO_PRESET_3   CAMERA_IP_PORT + CAMERA_COMMAND + GOTO_CAM_PRESET_3 + AUTH
// resolution
#define CAMERA_CONTROL_DEFAULT_RESOLUTION  CAMERA_IP_PORT + CAMERA_CONTROL   + SET_CAM_TO_DEFAULT_REZ + AUTH
#define CAMERA_CONTROL_VGA_RESOLUTION      CAMERA_IP_PORT + CAMERA_CONTROL   + SET_CAM_TO_VGA_REZ + AUTH
#define CAMERA_CONTROL_QVGA_RESOLUTION     CAMERA_IP_PORT + CAMERA_CONTROL   + SET_CAM_TO_QVGA_REZ + AUTH
// brightness
#define CAMERA_CONTROL_MIN_BRIGHTNESS  CAMERA_IP_PORT + CAMERA_CONTROL   + CAM_MIN_BRIGHTNESS + AUTH
#define CAMERA_CONTROL_1_BRIGHTNESS    CAMERA_IP_PORT + CAMERA_CONTROL   + CAM_1_BRIGHTNESS + AUTH
#define CAMERA_CONTROL_2_BRIGHTNESS    CAMERA_IP_PORT + CAMERA_CONTROL   + CAM_2_BRIGHTNESS + AUTH
#define CAMERA_CONTROL_3_BRIGHTNESS    CAMERA_IP_PORT + CAMERA_CONTROL   + CAM_3_BRIGHTNESS + AUTH
#define CAMERA_CONTROL_4_BRIGHTNESS    CAMERA_IP_PORT + CAMERA_CONTROL   + CAM_4_BRIGHTNESS + AUTH
#define CAMERA_CONTROL_5_BRIGHTNESS    CAMERA_IP_PORT + CAMERA_CONTROL   + CAM_5_BRIGHTNESS + AUTH
#define CAMERA_CONTROL_6_BRIGHTNESS    CAMERA_IP_PORT + CAMERA_CONTROL   + CAM_6_BRIGHTNESS + AUTH
#define CAMERA_CONTROL_7_BRIGHTNESS    CAMERA_IP_PORT + CAMERA_CONTROL   + CAM_7_BRIGHTNESS + AUTH
#define CAMERA_CONTROL_8_BRIGHTNESS    CAMERA_IP_PORT + CAMERA_CONTROL   + CAM_8_BRIGHTNESS + AUTH
#define CAMERA_CONTROL_9_BRIGHTNESS    CAMERA_IP_PORT + CAMERA_CONTROL   + CAM_9_BRIGHTNESS + AUTH
#define CAMERA_CONTROL_10_BRIGHTNESS   CAMERA_IP_PORT + CAMERA_CONTROL   + CAM_10_BRIGHTNESS + AUTH
#define CAMERA_CONTROL_11_BRIGHTNESS   CAMERA_IP_PORT + CAMERA_CONTROL   + CAM_11_BRIGHTNESS + AUTH
#define CAMERA_CONTROL_12_BRIGHTNESS   CAMERA_IP_PORT + CAMERA_CONTROL   + CAM_12_BRIGHTNESS + AUTH
#define CAMERA_CONTROL_13_BRIGHTNESS   CAMERA_IP_PORT + CAMERA_CONTROL   + CAM_13_BRIGHTNESS + AUTH
#define CAMERA_CONTROL_14_BRIGHTNESS   CAMERA_IP_PORT + CAMERA_CONTROL   + CAM_14_BRIGHTNESS + AUTH
#define CAMERA_CONTROL_15_BRIGHTNESS   CAMERA_IP_PORT + CAMERA_CONTROL   + CAM_15_BRIGHTNESS + AUTH

#define CAMERA_CONTROL_MID_BRIGHTNESS  CAMERA_IP_PORT + CAMERA_CONTROL   + CAM_7_BRIGHTNESS  + AUTH
#define CAMERA_CONTROL_MAX_BRIGHTNESS  CAMERA_IP_PORT + CAMERA_CONTROL   + CAM_15_BRIGHTNESS + AUTH
// contrast
#define CAMERA_CONTROL_MIN_CONTRAST   CAMERA_IP_PORT + CAMERA_CONTROL   + CAM_MID_CONSTRAST + AUTH
#define CAMERA_CONTROL_MID_CONTRAST   CAMERA_IP_PORT + CAMERA_CONTROL   + CAM_MID_CONSTRAST + AUTH
#define CAMERA_CONTROL_MAX_CONTRAST   CAMERA_IP_PORT + CAMERA_CONTROL   + CAM_MAX_CONSTRAST + AUTH
// freqenzy
#define CAMERA_CONTROL_MODE_50HZ      CAMERA_IP_PORT + CAMERA_CONTROL + CAM_SET_50HZ + AUTH
#define CAMERA_CONTROL_MODE_60HZ      CAMERA_IP_PORT + CAMERA_CONTROL + CAM_SET_60HZ + AUTH
#define CAMERA_CONTROL_MODE_OUTDOORS  CAMERA_IP_PORT + CAMERA_CONTROL  + CAM_SET_OUTDOORS  + AUTH

// flip and mirror
#define CAMERA_CONTROL_FLIP_MIRROR_NORMAL  CAMERA_IP_PORT + CAMERA_CONTROL + FLIP_AND_MIRROR_NORMAL + AUTH
#define CAMERA_CONTROL_FLIP              CAMERA_IP_PORT + CAMERA_CONTROL + FLIP + AUTH
#define CAMERA_CONTROL_MIRROR            CAMERA_IP_PORT + CAMERA_CONTROL + MIRROR + AUTH
#define CAMERA_CONTROL_FLIP_AND_MIRROR   CAMERA_IP_PORT + CAMERA_CONTROL  + FLIP_AND_MIRROR  + AUTH
// check user
#define CHECK_USER  CAMERA_IP_PORT + "check_user2.cgi?" + AUTH
// set alarm
#define SET_ALARM_MOTION_SENSITIVITY_0  CAMERA_IP_PORT + SET_ALARM + MOTION_SENSITIVITY_0 + AUTH
#define SET_ALARM_MOTION_SENSITIVITY_1  CAMERA_IP_PORT + SET_ALARM + MOTION_SENSITIVITY_1 + AUTH
#define SET_ALARM_MOTION_SENSITIVITY_2  CAMERA_IP_PORT + SET_ALARM + MOTION_SENSITIVITY_2 + AUTH
#define SET_ALARM_MOTION_SENSITIVITY_3  CAMERA_IP_PORT + SET_ALARM + MOTION_SENSITIVITY_3 + AUTH
#define SET_ALARM_MOTION_SENSITIVITY_4  CAMERA_IP_PORT + SET_ALARM + MOTION_SENSITIVITY_4 + AUTH
#define SET_ALARM_MOTION_SENSITIVITY_5  CAMERA_IP_PORT + SET_ALARM + MOTION_SENSITIVITY_5 + AUTH
#define SET_ALARM_MOTION_SENSITIVITY_6  CAMERA_IP_PORT + SET_ALARM + MOTION_SENSITIVITY_6 + AUTH
#define SET_ALARM_MOTION_SENSITIVITY_7  CAMERA_IP_PORT + SET_ALARM + MOTION_SENSITIVITY_7 + AUTH
#define SET_ALARM_MOTION_SENSITIVITY_8  CAMERA_IP_PORT + SET_ALARM + MOTION_SENSITIVITY_8 + AUTH
// enable or disable alarm
#define SET_ALARM_ENABLE    CAMERA_IP_PORT + SET_ALARM_ONLY + ENABLE_ALARM_COMMAND + AUTH
#define SET_ALARM_DISABLE   CAMERA_IP_PORT + SET_ALARM_ONLY + DISABLED_ALARM_COMMAND + AUTH
// enable mail with alarm , camera software can mail you if it detects motion
#define SET_ALARM_MAIL_ENABLE   CAMERA_IP_PORT + SET_ALARM_ONLY + ENABLE_MAIL_WITH_ALARM + AUTH
#define SET_ALARM_MAIL_DISABLE  CAMERA_IP_PORT + SET_ALARM_ONLY + DISABLE_MAIL_WTH_ALARM + AUTH
// set the second interval before the alrm uploads an image
#define SET_ALARM_SECONDS_TO_UPLOAD_OFF  CAMERA_IP_PORT + SET_ALARM_ONLY + UPLOAD_INTERVAL + "0" + AUTH
#define SET_ALARM_SECONDS_TO_UPLOAD_1  CAMERA_IP_PORT + SET_ALARM_ONLY + UPLOAD_INTERVAL + "1" + AUTH
#define SET_ALARM_SECONDS_TO_UPLOAD_2  CAMERA_IP_PORT + SET_ALARM_ONLY + UPLOAD_INTERVAL + "2" + AUTH
#define SET_ALARM_SECONDS_TO_UPLOAD_5  CAMERA_IP_PORT + SET_ALARM_ONLY + UPLOAD_INTERVAL + "5" + AUTH
#define SET_ALARM_SECONDS_TO_UPLOAD_10  CAMERA_IP_PORT + SET_ALARM_ONLY + UPLOAD_INTERVAL + "5" + AUTH
#define SET_ALARM_SECONDS_TO_UPLOAD_30  CAMERA_IP_PORT + SET_ALARM_ONLY + UPLOAD_INTERVAL + "30" + AUTH
#define SET_ALARM_SECONDS_TO_UPLOAD_60  CAMERA_IP_PORT + SET_ALARM_ONLY + UPLOAD_INTERVAL + "30" + AUTH
    }
}

#endif /* Foscam19810W_hpp */
