include(${CMAKE_CURRENT_LIST_DIR}/all.cmake)

set(ACTUAL_SYSTEM_NAME "darwin" CACHE STRING "" FORCE)

set(EVA_SDKROOT "${EVA_SDKS_PREFIX}/darwin")

set(CMAKE_SYSTEM_NAME "Darwin")

set(CMAKE_XCODE_ATTRIBUTE_SDKROOT "macosx")
set(CMAKE_XCODE_ATTRIBUTE_MACOSX_DEPLOYMENT_TARGET "10.10")
set(CMAKE_OSX_ARCHITECTURES "x86_64")

list(APPEND CMAKE_MODULE_PATH "${EVA_SDKROOT}/lib/cmake")

set(CMAKE_INSTALL_PREFIX "${EVA_SDKROOT}" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_NAME_DIR "${EVA_SDKROOT}/lib" CACHE STRING "" FORCE)

add_definitions(-DTARGET_OS_MAC=1)
